services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
      - app-networks
    volumes:
      - ./api:/api
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-networks
    depends_on:
      - api
    environment:
      - NODE_ENV=production
networks:
  app-networks:
    driver: bridge









































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































      
